import * as p from "@clack/prompts";
import pc from "picocolors";
import { readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { hasLocalConfig, isHeyflareProject, readJsonc, run, slug, wranglerCmd } from "./util.mjs";

const LOCAL = "wrangler.local.jsonc";

function bail(msg) {
  p.cancel(msg);
  process.exit(1);
}
function guard(v) {
  if (p.isCancel(v)) bail("Cancelled.");
  return v;
}

async function wrangler(args, opts = {}) {
  const [cmd, ...pre] = wranglerCmd();
  return run(cmd, [...pre, ...args], opts);
}

async function ensureLoggedIn(cwd, yes) {
  const s = p.spinner();
  s.start("Checking Cloudflare login");
  const who = await wrangler(["whoami"], { cwd, capture: true });
  const loggedIn = /logged in/i.test(who.out + who.err) && !/not authenticated|not logged in/i.test(who.out + who.err);
  if (loggedIn) {
    const m = (who.out + who.err).match(/associated with the email ([^\s.]+@[^\s.]+\.[^\s.]+)/i);
    s.stop(`Logged in to Cloudflare${m ? ` as ${m[1]}` : ""}`);
    return;
  }
  s.stop("Not logged in to Cloudflare");
  if (!yes) {
    const ok = guard(await p.confirm({ message: "Open the browser to log in with Wrangler?", initialValue: true }));
    if (!ok) bail("Log in first: npx wrangler login");
  }
  const r = await wrangler(["login"], { cwd });
  if (r.code !== 0) bail("Wrangler login failed.");
}

function parseD1Id(text) {
  const m = text.match(/"database_id"\s*:\s*"([0-9a-f-]{36})"/i) || text.match(/database_id\s*=\s*"([0-9a-f-]{36})"/i) || text.match(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i);
  return m ? m[1] : null;
}

function writeLocalConfig(cwd, { name, dbName, dbId, host }) {
  const base = readJsonc(join(cwd, "wrangler.jsonc"));
  const cfg = {
    $schema: base.$schema,
    name,
    main: base.main,
    compatibility_date: base.compatibility_date,
    compatibility_flags: base.compatibility_flags,
    rules: base.rules,
    assets: base.assets,
    d1_databases: [{ binding: "DB", database_name: dbName, database_id: dbId, migrations_dir: "migrations" }],
    triggers: base.triggers,
    vars: { ...(base.vars ?? {}), APP_NAME: base.vars?.APP_NAME ?? "heyflare", WORKER_NAME: name, ...(host ? { APP_URL: `https://${host}` } : {}) },
    ...(host ? { routes: [{ pattern: host, custom_domain: true }] } : {}),
    observability: base.observability ?? { enabled: true },
  };
  const text = `// Generated by create-heyflare. This file holds your own ids — keep it out of git (it is git-ignored).\n${JSON.stringify(cfg, null, 2)}\n`;
  writeFileSync(join(cwd, LOCAL), text);
  return cfg;
}

async function setSecret(cwd, name, value) {
  const r = await wrangler(["secret", "put", name, "-c", LOCAL], { cwd, capture: true, input: value + "\n" });
  return r.code === 0;
}

/**
 * Guided deploy. Options: { yes, cwd, secrets: { GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET } }.
 * Non-interactive with `yes` (defaults + env `HEYFLARE_NAME`, `HEYFLARE_HOST`, `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET`).
 */
export async function deploy({ cwd = process.cwd(), yes = false } = {}) {
  if (!isHeyflareProject(cwd)) bail(`This folder doesn't look like a heyflare project (no wrangler.jsonc + src/worker). Run this inside the project.`);
  p.intro(pc.bgWhite(pc.black(" heyflare · deploy ")));

  await ensureLoggedIn(cwd, yes);

  let cfg;
  if (hasLocalConfig(cwd)) {
    cfg = readJsonc(join(cwd, LOCAL));
    p.log.info(`Using existing ${LOCAL} (worker ${pc.bold(cfg.name)}${cfg.routes?.[0]?.pattern ? ` at ${cfg.routes[0].pattern}` : ""}).`);
  } else {
    const defName = slug(process.env.HEYFLARE_NAME || basename(cwd));
    const name = yes ? defName : slug(guard(await p.text({ message: "Worker name", initialValue: defName, validate: (v) => (v.trim() ? undefined : "Required") })));
    let host = process.env.HEYFLARE_HOST || "";
    if (!yes) {
      const choice = guard(
        await p.select({
          message: "Where should it live?",
          options: [
            { value: "workers", label: "A free *.workers.dev URL", hint: "quickest" },
            { value: "domain", label: "A custom domain on a zone in my Cloudflare account", hint: "e.g. mail.example.com — no existing DNS record for that host" },
          ],
        })
      );
      if (choice === "domain") host = String(guard(await p.text({ message: "Hostname", placeholder: "mail.example.com", validate: (v) => (/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(v.trim()) ? undefined : "Enter a hostname like mail.example.com") }))).trim().toLowerCase();
    }
    const dbName = `${name}-db`;
    const s = p.spinner();
    s.start(`Creating D1 database ${dbName}`);
    const r = await wrangler(["d1", "create", dbName], { cwd, capture: true });
    let dbId = parseD1Id(r.out + r.err);
    if (!dbId && /already exists/i.test(r.out + r.err)) {
      const list = await wrangler(["d1", "list", "--json"], { cwd, capture: true });
      try {
        const rows = JSON.parse(list.out);
        dbId = rows.find((d) => d.name === dbName)?.uuid ?? null;
      } catch {}
    }
    if (!dbId) {
      s.stop("Could not create the database");
      p.log.error((r.out + r.err).trim().slice(-800));
      bail("D1 creation failed.");
    }
    s.stop(`D1 database ${dbName} ready (${dbId.slice(0, 8)}…)`);
    cfg = writeLocalConfig(cwd, { name, dbName, dbId, host });
    p.log.success(`Wrote ${LOCAL}`);
  }

  // Build + deploy (secrets go in afterwards so the Worker exists).
  const b = p.spinner();
  b.start("Building the app");
  const build = await run(process.platform === "win32" ? "npm.cmd" : "npm", ["run", "build"], { cwd, capture: true });
  if (build.code !== 0) {
    b.stop("Build failed");
    p.log.error((build.out + build.err).trim().slice(-1500));
    bail("Build failed.");
  }
  b.stop("Built");
  p.log.step("Deploying with Wrangler…");
  const d = await wrangler(["deploy", "-c", LOCAL], { cwd, capture: true, echo: true });
  if (d.code !== 0) bail("Deploy failed (see output above).");
  const urlMatch = (d.out + d.err).match(/https:\/\/[a-z0-9.-]+\.workers\.dev/i);
  const url = cfg.routes?.[0]?.pattern ? `https://${cfg.routes[0].pattern}` : urlMatch ? urlMatch[0] : null;

  // Google OAuth secrets (optional).
  const envId = process.env.GOOGLE_CLIENT_ID;
  const envSecret = process.env.GOOGLE_CLIENT_SECRET;
  let setNow = !!(envId && envSecret);
  if (!setNow && !yes) {
    setNow = guard(
      await p.confirm({
        message: `Add your Google OAuth client now? (needed to connect Gmail — redirect URI: ${url ?? "https://<your host>"}/auth/google/callback)`,
        initialValue: false,
      })
    );
  }
  if (setNow) {
    const id = envId || String(guard(await p.text({ message: "GOOGLE_CLIENT_ID", validate: (v) => (v.trim() ? undefined : "Required") }))).trim();
    const secret = envSecret || String(guard(await p.password({ message: "GOOGLE_CLIENT_SECRET", validate: (v) => (v.trim() ? undefined : "Required") }))).trim();
    const s2 = p.spinner();
    s2.start("Storing secrets on the Worker");
    const ok1 = await setSecret(cwd, "GOOGLE_CLIENT_ID", id);
    const ok2 = await setSecret(cwd, "GOOGLE_CLIENT_SECRET", secret);
    s2.stop(ok1 && ok2 ? "Secrets stored" : "Could not store secrets (set them later in Workers → Settings → Variables and Secrets)");
  }

  p.note(
    [
      url ? `${pc.bold(url)}` : "Open your Worker URL",
      "",
      "1. Open the URL → you'll land on /setup to create your login.",
      "2. Connect Gmail from the sidebar (needs the Google secrets).",
      "3. Settings → AI to add a model key for the assistant.",
      "",
      "The app applies its database migrations itself on first request.",
      `Redeploy any time with ${pc.cyan("npm run deploy")}.`,
    ].join("\n"),
    "Deployed"
  );
  p.outro("Enjoy your calm inbox.");
  return { url, config: cfg };
}
