// Generated by scripts/gen-version.mjs — do not edit by hand.
// Committed with safe defaults so a fresh clone type-checks; `npm run build` overwrites it.
export const VERSION = "0.1.0";
export const COMMIT = "unknown";
export const BUILT_AT = "1970-01-01T00:00:00.000Z";
